### ISSUE TITLE
suggestion: add a overflow cover for fluid tanks

### ISSUE THREAD

**Issue by DoomSquirter** [alkcorp/GTplusplus#362]
# Issue Title  
 Provide a general summary of the issue in the Title above, 
 Something descriptive and related to the issue + Mod Version in [].
 Example `Custom GT++ Alveary Frame Blocks do not work [v1.5.0-alpha]`

a cover that outputs only from that covered when full would be useful.  then goes to fluid trash
meant, u can then put a fluid trash can on other side of cover or whatever
doesn't even have to be called a void or anything (is where it started in the conversation)

an alternative would be a void.  some cover or tank that auto voids fluids once full

## Expected Behavior
 If you're describing a bug, tell us what you expect should happen.   
 If you're suggesting a change/improvement, tell us how it should/could work.  

## Current Behavior
 If describing a bug, tell us what happens instead of the expected behavior. 
 If suggesting a change/improvement, explain the difference from current behavior. 

## Possible Solution
 Not obligatory, but suggest a fix/reason for the bug, 
 or ideas how to implement the addition or change. 

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1.
 2.

## Context
 How has this issue affected you? What are you trying to accomplish? 
 Providing context helps us come up with a solution that is most useful. 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  
 * Version used:
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version:
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by Highbeam** [comment]
I asked for similar on GTNH github:  https://github.com/GTNewHorizons/NewHorizons/issues/3182

I currently manage this with a condensed set up:

Fluid cover (inverted) - dense redstone crystal (set to 14) on cover pointing up to translocator with glowstone/redstone upgrade into trash.  But it would be so much simpler to do this in 1 cover.

I'd prefer an 'overflow' cover rather than void for both items and fluids.

Screenshots of the design below:

![2018-08-31_12 27 23](https://user-images.githubusercontent.com/32101225/44907738-451b3a00-ad19-11e8-8758-a23afc9a2df5.png)

![2018-08-31_12 28 29](https://user-images.githubusercontent.com/32101225/44907796-857ab800-ad19-11e8-8a6e-493c5e715111.png)

![2018-08-31_12 29 21](https://user-images.githubusercontent.com/32101225/44907802-890e3f00-ad19-11e8-8a22-17f7560d2b76.png)

**Comment by draknyte1** [comment]
It voids anything fluid > the max amount set in the cover. So if it overflows, it's essentially getting voided.

**Comment by draknyte1** [comment]
![voidcover](https://user-images.githubusercontent.com/3060479/44908282-3d31b900-ad5e-11e8-8721-9380e3689f61.gif)
![voidcoverimage2](https://user-images.githubusercontent.com/3060479/44908287-40c54000-ad5e-11e8-820e-a5fa0c304940.jpg)

**Comment by Highbeam** [comment]
not sure what I'm looking at here?  is there a cover on the fluid tank or the output hatch?

can it go negative so you can put it on a super tank (4mil storage) and then set the cover to void if the tank is Limit -1000 (void at 3999000)?

**Comment by Highbeam** [comment]
I still like the idea of an overflow cover - so if you put it on a side of the super tank, it will only output on that side of the contents are > amount

**Comment by draknyte1** [comment]
It's a cover for any 'machine' that accepts covers. 

If it contains more than the amount set on the cover, it 'overflows' into the void. There is no 'overflow out' into another tank feature. The positive values in the second photo show this 'max' value being set. Different tier covers have higher maximum amounts, to scale for tanks as you tier up.

**Comment by draknyte1** [comment]
Implemented and now working.
