### ISSUE TITLE
Large Electrolyzer destroying correct materials

### ISSUE THREAD

**Issue by Lithorn** [alkcorp/GTplusplus#388]
# Issue Title  
Large Electrolyzer is destroying/consuming Sodium Bisfulate and returning nothing. 

## Expected Behavior
Input Sodium Bisfulate, get hydrogen and Sodium Persfulate. According to NEI the large Elec dosent require cells, and outputs two fluids? I've tried with a cell and material, with 1x In/out Hatch and Bus. I've also tried with 2x Output Hatches to catch both fluids? It does not show needing a circuit?

## Current Behavior
Toss in Sodium Bisfulate into input bus, gets consumed with no return of output. 

## Steps to Reproduce (for bugs)
Just put Sodium Bisfulate into a large Electrolyzer.

## Context
I was trying to complete the revamped Sodium Persfulate quest in GTNH 2.0.5.1

## Game Environment
 
 * GTNH
 * 2.0.5.1

Also include:
 * gregtech-5.09.32.36
 *industrialcraft-2-2.2.828a-experimental
 * Java version: 1.8.0 - 181
 * Operating System: W10X64 Pro

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ X]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ X]    Multi Player?

**Comment by draknyte1** [comment]
The large electrolyzer, Centrifuge & Adv. Vac Freezer generate their recipes from the Original machines recipe map. Whenever cells are encountered as input, It simply asks the Fluid Registry what fluid is in the cell, then removes the cell and adds a fluid input.

Vanilla GT has no way to create or use Sodium Persfulate, so I can't really debug this without several loads of GTNH. There are many cases where GTNH has fluids without cells or cells with no fluid, in which case recipes may error out. Technically, not my issue to fix, however these should already be ignored.

**Comment by Ghengis88** [comment]
Do you have only 1 output hatch?
