### ISSUE TITLE
Texture of pipe not change when setting "Input disable".

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#396]
Also reported in GTNH GTNewHorizons/NewHorizons/issues/3790

## Expected Behavior
When set Pipe of GT++ alloy's to "Input disable" by Wrench Shift+Right click, Texture of pipe is changed.

## Current Behavior
Texture of pipe is not changed.
![2018-10-26_13 46 55](https://user-images.githubusercontent.com/40425798/47601776-65f9c600-da10-11e8-87bd-27720049cade.png)

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:GTNewHorizons ver2.0.5.1
 * Version used:1.7.02.09

Also include:
 * Gregtech version:5.09.32.36
 * IC2 version:2.2.828a-experimental
 * Java version:Java1.8.0_191
 * Operating System:Windows 10 Pro 64bit & CentOS7 64bit

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Due to this horrible handling of pipes by the developers over the years, without looking I'll say no I won't fix this issue. Keep in mind I must retain compatibility with Gt 5.08.x as well, so some things may not be possible.

**Comment by draknyte1** [comment]
As stated above, won’t fix. A minor visual issue vs losing backwards compatibility isn’t worth it, sorry.
