### ISSUE TITLE
Crash with versions 1.7.0 onwards

### ISSUE THREAD

**Issue by Drymouthman** [alkcorp/GTplusplus#412]
# Issue Title  
I'm running my own modified instance of Infitech 2. The game loads just fine with GT++ 1.6.110, but if I try to update to 1.7.0 onwards (deleting the configs of course) I get a crash related to gtPlusPlus.core.material.ELEMENT

## Expected Behavior
Well, it should load.

## Current Behavior
Minecraft crashes while loading.

## Possible Solution
-

## Steps to Reproduce (for bugs)
 Tried every version from 1.7.0 onwards, getting the same result in every case.

## Context
I'm trying to get newer versions of this mod to work on a modified instance of infitech 2.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  Infitech 2 (modified, added mainly thaumcraft addons, but I think this crash might be unrelated to those). A third-party pack on the FTB launcher.
 * Version used: 3.2.21

Log: https://pastebin.com/M0EB2EZh

Also include:
 * Gregtech version: gregtech-5.09.32pre5
 * IC2 version: industrialcraft-2-2.2.828-experimental
 * Java version:  1.8.0_161
 * Operating System: Windows 7 64 bit.

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Try with https://minecraft.curseforge.com/projects/gregtech-gt-gtplusplus/files/2608712

**Comment by Drymouthman** [comment]
Okay, tried it again and got more-or-less the same error. Log here: https://pastebin.com/96XBzH6g

**Comment by draknyte1** [comment]
Can you try with https://cdn.discordapp.com/attachments/450164459835490304/546146264136417298/GT-PlusPlus-1.7.02.88-debug.jar ?

Sorry for the rather late response to this.
