### ISSUE TITLE
Reduce Extruder recipes for materials by 2 EU tier(s) to fit respective tiers

### ISSUE THREAD

**Issue by ScriptedPiky** [alkcorp/GTplusplus#428]
As title says, reduce the current extruder recipes by 2 EU tiers to fit the respective tiers of where they currently are now, as it makes most of the recipes extremely difficult to obtain (for instance: getting a UV extruder or two ZPM energy hatches on an extruder multiblock to get an LuV recipe such as the Autocrafter Frame)
Makes getting certain parts for machines, casings, and other things absolutely ridiculous. Shown: LuV recipe, UV recipe
![image](https://user-images.githubusercontent.com/41557212/53298255-0bb31b00-37e0-11e9-81f1-649c7b490d71.png)
![gtplusplus1](https://user-images.githubusercontent.com/41557212/53298261-271e2600-37e0-11e9-8f6b-b721eb5a3343.PNG)

**Comment by draknyte1** [comment]
Extrusion recipes and several other things use the exact same logic GT does. Molecular mass voltage determination, Whilst things like ABS recipes use a rather simple tiering system for voltage. Every 1k melting point temp is +1 to voltage tier.
