### ISSUE TITLE
Free and fast Oxygen with HG-1223

### ISSUE THREAD

**Issue by DietmarKracht** [alkcorp/GTplusplus#434]
# Issue Title  
HG-1223 Free Oxygen

## Current Behavior
 Creating HG-1223 takes a mercury cell, 2 barium , 2 calcium and 3 copper in a Mixer and creates a liquid that is worth 16 Ingots. Pulverize these to get the dust. You can then centrifuge it into its components and get 8000 Oxygen additionally

## Context
 The processing times are really fast so its a good source of early oxygen.

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x ]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x ]    Multi Player?

**Comment by draknyte1** [comment]
What version?

I Redid the recipes for HG-1223 for 6.8 for other reasons. Oxygen should be a part of it's creation iirc.

**Comment by Dream-Master** [comment]
gues version GT++ V1.7.02.09
