### ISSUE TITLE
[1.7.02.99.pre.Build 303] Power Station Control Node does not recognise maintenance.

### ISSUE THREAD

**Issue by TwoTailedFox** [alkcorp/GTplusplus#440]
## Expected Behavior
As with other Multiblocks, the controller block should recognise when maintenance has been performed using the Maintenance Hatch

## Current Behavior
Currently, while the multiblock controller makes it clear that maintenance is required, the multiblock does not recognise when maintenance has been performed. Taking out and putting the Maintenance Hatch back does not solve the problem. Using Duct Tape also does not help.

## Possible Solution
Was working previously, possible code regression.

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1. Wait for maintenance to be needed.
 2. Attempt to fix.
 3. ????
 4. Fail to fix.

## Context
Was using as normal when Multiblock suddenly powered down. Further inspection revealed maintenance was overdue.

## Game Environment
If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

https://gamicus.gamepedia.com/index.php?title=User:TwoTailedFox/Current_Minecraft_Mods

Also include:
 * Gregtech version: gregtech-5.09.32pre5
 * IC2 version: industrialcraft-2-2.2.828-experimental
 * Java version: Java 8 Build 181
 * Operating System: Windows 10 Pro October 2018 Update

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [    ]    Using GT:NH/GT:New Horizons?
 - [ x ]    Single Player?
 - [    ]    Multi Player?

**Comment by TwoTailedFox** [comment]
This worked on a world reload, but it should probably still be looked into anyway for those that run this on servers.

**Comment by TwoTailedFox** [comment]
Power Station *also* seems to go offline with Error Code 64 (despite showing all green on the GUI) frequently, which only disappears on reloading the world.

**Comment by draknyte1** [comment]
Can you check this is still an issue?

**Comment by TwoTailedFox** [comment]
The problem with this issue is that it's intermittent. As this is from 40 builds previous, I'd say close this issue for now; if it happens again I can always re-comment.
