### ISSUE TITLE
[1.7.02.99.pre.Build 303] Unable to obtain Niobium-Titanium

### ISSUE THREAD

**Issue by TwoTailedFox** [alkcorp/GTplusplus#441]
## Expected Behavior
GregTech 5U allows Niobium-Titanium to be obtained by smelting 1 Titanium Ingot and 1 Niobium Ingot in the Blast Furnace.

## Current Behavior
Once GT++ is loaded, this recipe disappears from NEI, and the recipe does not trigger in the furnace (the furnace converts Titanium Ingots to Hot Titanium Ingots instead)

## Possible Solution
Was able to create this alloy previously, possible regression in code.

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1. Create new instance of Minecraft with mods below.
 2. Run.
 3. Attempt to make Niobium-Titanium.

## Context
This removes a crucial piece from progression, as Niobium-Titanium wires are used frequently in LuV machine and component recipes.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  
 * Version used:
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

* CodeChickenCore 1.0.7.47
* CoFHCore 3.1.4-329
* Forestry 4.2.16.64
* GregTech 5 Unofficial 5.09.32pre5
* GregTech++ 1.7.02.99 Build 303
* IndustrialCraft 2 2.2.828-experimental
* NotEnoughItems 1.0.5.120

Also include:
 * Gregtech version: 5.09.32pre5
 * IC2 version: 2.2.828-experimental
 * Java version: Java 8 Build 181
 * Operating System: Windows 10 Pro October 2018 Update

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [ x ]    Single Player?
 - [ ]    Multi Player?

**Comment by TwoTailedFox** [comment]
Have been running worlds incrementally with older GT++ builds. The issue doesn't appear GT-PlusPlus-1.7.02.09, but does as of GT-PlusPlus-1.7.02.50 onwards (cannot test .24 and .25 due to crashes)

**Comment by draknyte1** [comment]
It’s related to the hot I got recipe I readded. Guess vanilla GT considers them conflicting and doesn’t add the second recipe.

**Comment by TwoTailedFox** [comment]
Same issue also applies to Niobium Nitride. All other GT ingots check out.
