### ISSUE TITLE
Maintenance Overload

### ISSUE THREAD

**Issue by DietmarKracht** [alkcorp/GTplusplus#446]
# Issue Title  
 I don't know if its intended or a bug. I currently process large quantities of awakened draconium in an Advanced EBF with UHV Energy Hatch and i get random maintenance issues every 1-2 hours.

## Expected Behavior
There should be a larger dely between maintenance issues

## Game Environment
 I am using the GT++ version on the official GTNH Servers

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
You get maint. Issues every tick there’s not enough Pyrotheum. It’s fairly intended in that case.

**Comment by DietmarKracht** [comment]
I do have enough pyrotheum. Although i have a core module with no core inside. Might that be the cause?

**Comment by DietmarKracht** [comment]
Seems do be an issue with a running advanced ebf at server restart.
Maybe the pyrotheum isnt recognized properly.

**Comment by DietmarKracht** [comment]
So this happens only to the advanced ebfs. Other gt++ Multis keep running without maintenance issues at the server restart
