### ISSUE TITLE
Circuit programmer is sometimes translucent.

### ISSUE THREAD

**Issue by Anarack** [alkcorp/GTplusplus#447]
# Issue Title  
The circuit programmer with a project red inverted lamp behind it is translucent. 

## Expected Behavior
You should not see through a machine.

## Current Behavior
I can see through the machine.

## Steps to Reproduce (for bugs)
![2019-03-20_21 58 13](https://user-images.githubusercontent.com/20565115/54731328-b4dcff00-4b5b-11e9-9018-173d05caf08d.png)

## Game Environment
GT:NH 2.0.7.0
GT-PlusPlus-1.7.02.89-beta
gregtech-5.09.33.12
industrialcraft-2-2.2.828a-experimental
fastcraft-1.23

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
As the Circuit programmer is rendered as a standard block, it’s not my fault.
