### ISSUE TITLE
HG-1223 does not want to be produced

### ISSUE THREAD

**Issue by Glammi** [alkcorp/GTplusplus#448]
# Issue Title  
HG-1223 does not want to be produced

## Expected Behavior

i try to produce HG-1223

Blast Alloy Smelter
ZPM Energy Hatch
ZPM Control Core

Programmed Circuit =5
1x Mercury Cell
2x Barium Dust
2x Calcium Dust
3x Copper Dust
8000 mb Oxygen Gas

## Current Behavior
Machine does't start

I tried some other recipes and they worked

## Possible Solution
fix it please

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?
Server: myftb.de
Version: 2.0.7.0

**Comment by TwoTailedFox** [comment]
Do you have a muffler?

**Comment by Glammi** [comment]
@TwoTailedFox 
Current Behavior
...
I tried some other recipes and they worked
