### ISSUE TITLE
Eglin Steel has unintended lathe recipe

### ISSUE THREAD

**Issue by LogicFalls** [alkcorp/GTplusplus#449]
In GTNH v2.0.70, Eglin steel ingots have a strange and likely unintended lathe recipe. one ingot produces one rod with no by-product, and takes a single tick to process at LV. Screenshot illustrates recipe.

This makes the HV extruder necessary to produce Eglin rods efficiently, gating the large sifter until after acquiring EV circuits

### Misc Info
 Check all that apply

 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?
![image](https://user-images.githubusercontent.com/32601565/54881322-a6863000-4e46-11e9-89fa-9a62bda6f942.png)

**Comment by draknyte1** [comment]
Does this apply for all material lathe recipes from GT++?

**Comment by LogicFalls** [comment]
Yes, it seems all GT++ metals have abnormally low process times and no secondary output.

**Comment by ScriptedPiky** [comment]
> Does this apply for all material lathe recipes from GT++?

Yes. It applies to **all** lathe and extruder recipes. I even made a post about this stating that all the GT++ metal recipes have +2 EU/t tiers applied to extruder recipes for some reason; gating them beyond what they normally should normally be. For instance: Zeron-100 is a LuV Alloy Smeltery recipe, but has a UV Extruder recipe
https://github.com/alkcorp/GTplusplus/issues/428
