### ISSUE TITLE
Unintended Fertilizer Recipe Loop in GTNH

### ISSUE THREAD

**Issue by chochem** [alkcorp/GTplusplus#451]
Playing GT:NH in version 2.0.7.0 (with GT++ version 1.7.02.24).

There is a way to make Fertilizer (Forestry or IC2) very cheaply which seems unintended:

1. Mixer: 8 IC2 Fert. + 1 Apatite dust + 1Bucket Water = 30 Forestry Fert.
2. Fluid Extractor: 1 Forestry Fert. = 144L Fluid Fert.
3. Centrifuge: 144L Fluid Fert. = 1 IC2 Fert.

Overall 1Bucket  Water + 1 Apatite dust makes 22 Fertilizer (of either type) which makes every other recipe obsolete in comparison.

I am pretty sure 1. is intended thus making IC2 Fertilizer 'more valuable' than Forestry Fert. So probably 2. and 3. should have matching solid fertilizer.

Bluebine says this should be a GT++ recipe which is why I am posting here,

**Comment by draknyte1** [comment]
7.0 should have 1.7.02.86 or something (Some weird beta build that wasn't meant to exist past 6.8)

I'll take a look.

**Comment by 0lafe** [comment]
>Centrifuge: 144L Fluid Fert. = 1 IC2 Fert.

That's a new recipe that probably shouldn't exist. Problem with breaking down ferts is that there is no 1 recipe for them. So giving them a way to be broken down into something static presents some issues. It's more meant as a 1 way system (at least for NH, i have no idea how many ic2->forestry recipes exist outside of it)

**Comment by draknyte1** [comment]
> Centrifuge: 144L Fluid Fert. = 1 IC2 Fert.

Dunno who adds this recipe, but it doesn't exist in my dev environment.
![image](https://user-images.githubusercontent.com/3060479/56784406-a0afb000-6833-11e9-9c81-094090a64441.png)
![image](https://user-images.githubusercontent.com/3060479/56784413-a9a08180-6833-11e9-8862-5c9503a0981c.png)

As we can see here, `fluid.fertiliser` has 0 uses besides canning.

**Comment by chochem** [comment]
blame bluebine ;). I will post it in new horizons issues.
