### ISSUE TITLE
1.7.02.24: Mixer Input Busses not separated

### ISSUE THREAD

**Issue by DietmarKracht** [alkcorp/GTplusplus#452]
# Issue Title  
The input busses of a mixer are no longer used separated from each other.

## Expected Behavior
Process each mixer recipe in each input bus separate from the other.

## Current Behavior
2 input bus, one with circuit 1, one with circuit 2

Mixer Recipe A: circuit no 1, ingrediant x,y,z 
Mixer Recipe B: circuit no 2, ingrediant x,z

Problem is if you process recipe A even if there is the circuit 1 in the same bus with all the ingrediant it still might recognize circuit 2  - EVEN though its not in the same bus - and process recipe B.
I experienced this problem at first with indium

## Game Environment

 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.0.7.0
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version:
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ x]    Multi Player?

**Comment by draknyte1** [comment]
Implemented in recent push.
