### ISSUE TITLE
[GTNH] RainForest tree not oredicted correctly[1.7.02.89-beta]

### ISSUE THREAD

**Issue by Cinobi** [alkcorp/GTplusplus#454]
# Issue Title  
 Provide a general summary of the issue in the Title above, 
 Something descriptive and related to the issue + Mod Version in [].
 Example `Custom GT++ Alveary Frame Blocks do not work [v1.5.0-alpha]`

## Expected Behavior
GT++ Rainforest oak logs processed in pyrolyse oven and GT++ Rainforest oak saplings can be used in autofarms like EIO farmer

## Current Behavior
Pyrolyse oven and EIO farmer do not recognize logs and saplings like items to process
## Possible Solution

Oredict it correctly? xD

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1. Place EIO farmer\ pyrolyse oven
 2. Insert Saplings\logs
 3.  ....

## Context
Can't use this great tree for heavy oil

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  
 * Version used:
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version:
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by Anarack** [comment]
For the charcoal pit, every log must be faced up or down for it to work.

**Comment by TimDiekmann** [comment]
> For the charcoal pit, every log must be faced up or down for it to work.

I tested it again, every log has to be placed upwards. So it has to be placed from bottem to top.
