### ISSUE TITLE
Hi-Amp Transformer can only use One type of circuit

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#458]
# Issue Title  
Hi-Amp Transformer can only use One type of circuit [GT-PlusPlus-1.7.02.89-beta]`

## Expected Behavior
LuV Hi-Amp Transformer can use All type of LuV circuit.
ZPM Hi-Amp Transformer can use All type of ZPM circuit.
UV Hi-Amp Transformer can use All type of UV circuit.

## Current Behavior
LuV Hi-Amp Transformer can only use of Mainframe.
ZPM Hi-Amp Transformer can only use of NanoprocessorMainframe.
UV Hi-Amp Transformercan only use of UltimateCrystalcomputer.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:GT New Horizons
 * Version used:2.0.6.8 and 2.0.7.0

Also include:
 * Gregtech version:gregtech-5.09.33.10 and gregtech-5.09.33.12
 * IC2 version:industrialcraft-2-2.2.828a-experimental
 * Java version:1.8.0_201
 * Operating System:Windwos10 Pro and CentOS7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by DietmarKracht** [comment]
Shouldn't these actually use coils instead of circuits?

**Comment by draknyte1** [comment]
They should and now do once again.
