### ISSUE TITLE
[Build 323] Wash Plant Recipes

### ISSUE THREAD

**Issue by TwoTailedFox** [alkcorp/GTplusplus#462]
## Expected Behavior
Wash Plant should produce purified ore and by-products.

## Current Behavior
Wash Plant consumes input items, but does not produce output items.

## Possible Solution
Fix regression.

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1. Build Wash Plant
 2. Activate

## Context
Unable to process ores.

## Game Environment
If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: https://gamicus.gamepedia.com/index.php?title=User:TwoTailedFox/Current_Minecraft_Mods&profile=no

Also include:
 * Gregtech version: 5.09.32pre5
 * IC2 version: 2.2.828-experimental
 * Java version: Java 8, Build 202
 * Operating System: Windows 10 October 2018 Update

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [ x ]    Single Player?
 - [ ]    Multi Player?

**Comment by NoriSilverrage** [comment]
I just want to throw in there, that the same issue is happening for the centrifuge.
