### ISSUE TITLE
Can't obtain ControlCore[ZPM]

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#467]
# Issue Title  
Can't obtain ControlCore[ZPM] [1.7.02.89-beta]`

## Expected Behavior
I can obtain ControlCore[ZPM]

## Current Behavior
I can't obtain ControlCore[ZPM], because ABS with ZPM voltage is required to obtain HG-1223 which is the material of ControlCore[ZPM]

## Possible Solution
Adding HG-1223 Dust Recipe or voltage to reducing voltage of smelting HG-1223.

## Game Environment
 * Modpack Name:GT New Horizons  
 * Version used:2.0.6.8

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version:gregtech-5.09.33.10
 * IC2 version:industrialcraft-2-2.2.828a-experimental
 * Java version:1.8.0_201
 * Operating System:Windwos10 Pro

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Fixed pending 7.1+.

Control cores are no longer required, I suggest you manually update following the instructions within the ReadMe.

**Comment by yukieiji** [comment]
Does that mean that the currently(enabling on ver2.0.7.2dev) enabled ControlCore will be disabled in the next GTNH version?

**Comment by draknyte1** [comment]
Yes. 

The latest version in Zeta (dunno dev version) should already have them as optional.
