### ISSUE TITLE
Essence in chest causing crash

### ISSUE THREAD

**Issue by NoriSilverrage** [alkcorp/GTplusplus#472]
# Issue Title  
Opening a chest with essence from TC crashes client.

## Details
I have a wisp farm that drops lots of essences. Apparently one of them contained a aspect called custom1. Opening a chest with one of these crashes the client out. I believe this aspect was removed in a recent patch.
~edit: bart NBT edited out custom1 but now there is a custom3 crashing as well.

## Possible Solution
Possibly revert change that removed the aspect.

## Steps to Reproduce (for bugs)
I'm not sure how you could easily reproduce this. I guess if you have a save that you know contains the aspects.

## Context
 How has this issue affected you? What are you trying to accomplish? 
 Providing context helps us come up with a solution that is most useful. 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:

[crash-2019-05-02_17.31.32-client.txt](https://github.com/alkcorp/GTplusplus/files/3140349/crash-2019-05-02_17.31.32-client.txt)

 * Modpack Name:  GTNH
 * Version used: 2.0.7.0

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ *]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [* ]    Multi Player?

**Comment by DoomSquirter** [comment]
is this going to be fixed before gtnh rolls out 7.3?  

guaranteed, there are going to be a bunch of broken worlds if this isn't fixed/reverted.
