### ISSUE TITLE
Tiered cover plates 

### ISSUE THREAD

**Issue by kekzdealer** [alkcorp/GTplusplus#475]
![image](https://user-images.githubusercontent.com/31353359/57543962-3c720d80-7356-11e9-85e4-a94cddcfdf11.png)

**Comment by sleepylucy** [comment]
https://i.kym-cdn.com/photos/images/newsfeed/000/993/875/084.png

**Comment by sleepylucy** [comment]
Posting images on mobile GitHub is hard

**Comment by SampsaxD** [comment]
For covering cables so it actually looks like part of the machine https://i.imgur.com/Ujfd7yy.jpg
