### ISSUE TITLE
Something to kill butterflys

### ISSUE THREAD

**Issue by Jocroy** [alkcorp/GTplusplus#486]
You hinted in Discord, that you could add something better than a command block for killing those pesky butterflys. So yeah, please do. Possibly make it a tree in analogy to the Cthaeh from King Killer Chronicles by Patrick Rothfuss.

**Comment by richardhendricks** [comment]
It could be a multiblock "machine" that is made with tree logs and leaves. A low tech magical formula or infusion to "awaken" it.

https://kingkiller.fandom.com/wiki/The_Cthaeh
![image](https://user-images.githubusercontent.com/1214811/57801630-bbca5d00-7719-11e9-9b2c-a7eb4a0aae82.png)
![image](https://user-images.githubusercontent.com/1214811/57801673-d8ff2b80-7719-11e9-9147-28abddb7ff87.png)
![image](https://user-images.githubusercontent.com/1214811/57801708-eae0ce80-7719-11e9-8adc-b7cc46410b5f.png)

If we could add some audio recordings to it, that would be really really cool.

**Comment by draknyte1** [comment]
Added Pest Killer in https://github.com/alkcorp/GTplusplus/commit/e6d7cf441f1e773d50d87469fb29e96782840e54.

**Comment by richardhendricks** [comment]
:-)

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5339
