### ISSUE TITLE
7.3 crash twice

### ISSUE THREAD

**Issue by BlackFlameTNT** [alkcorp/GTplusplus#492]
Which modpack version are you using?
2.0.7.3
single player crash twice at ross128
crash-2019-05-28_09.14.50-client.txt

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Ross128 isn’t my planet, it’s from BartWorks.

**Comment by BlackFlameTNT** [comment]
Yes I know but moron told me to post it in both github

**Comment by bartimaeusnek** [comment]
@draknyte1 this is caused by an older version of gt++, we must update, you can close this.
https://github.com/alkcorp/GTplusplus/issues/479
