### ISSUE TITLE
[1.7.02.99-pre] Advanced Muffler not working

### ISSUE THREAD

**Issue by DV666** [alkcorp/GTplusplus#496]
# [1.7.02.99-pre] Advanced Muffler not working
Version : GT-PlusPlus 1.7.02.99-pre

Since last updade on GTNH, EV Advanced Muffler not working anymore on my EBF and Multi-Smelter

## Expected Behavior
Uh... functionnal machine and less pollution ? :]

## Current Behavior
On my previous live session, my EBF (4 connected) and my multi-smelter didn't work since last GTNH update 2.0.7.5. Works perfectly before ofc.

When i activate my EBF, it stop immediately (similar to energy loss).

After some tests on my creative save, i found we need air filter on Advanced Muffler (good idea imo because too powerfull before ^^).
It's an EV Advanced Muffler so T1 Air Filter needed... but when i insert this item, it dissapear on HUD :( and machine can't process.

Another statement, machine can work with advanced muffler without air filter. After some operation, machine will stuck... weird.

## Possible Solution
Hey, you're the doc, Doc.

## Steps to Reproduce (for bugs)
Just build a multi-block machine on creative save and use advanced muffler (in my case, it's an EV-tier)

[Twitch video, at 01:50:40 (sorry, baguette in the place!)](https://www.twitch.tv/videos/440416596)

## Game Environment
 * Modpack Name:  GTNH
 * Version used: 2.0.7.5

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player? => Private server

**Comment by Zafaranec** [comment]
I have a same problem, any progress?
