### ISSUE TITLE
Quest failture Sun of the Sun at HV Level

### ISSUE THREAD

**Issue by Ngar1** [alkcorp/GTplusplus#497]
# Issue Title  
2.0.7.0

## Expected Behavior
Quest failture:
Power of the Sun at HV Level needs HV instead EV Superconductor, as it need for the receipt 

## Current Behavior
HV Superconductor

## Possible Solution
Change to EV Superconductor

## Steps to Reproduce (for bugs)
solve Quest

## Context
It is not very relevant.

## Game Environment
myftb

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [X ]    Multi Player?

**Comment by Dream-Master** [comment]
@Ngar1 This is not a gt++ issue post it here please.
https://github.com/GTNewHorizons/NewHorizons/issues

HV Pannels tier hv need materials hv+1 or +2 ties. That is intended.
