### ISSUE TITLE
Wearing the Charge Pack in your baubles slot and picking up redstone corrupts the player

### ISSUE THREAD

**Issue by observeroftime02** [alkcorp/GTplusplus#505]
# Issue Title  
As requested, crossposting from GTNH git. Wearing the charge pack and picking up redstone dust kicks the player from the server and corrupts the player character data.

## Expected Behavior
I expect nothing to happen and redstone dust to not interact with the charge pack .

## Current Behavior
It does interact with the charge pack in a way that causes loss of the player data.

## Possible Solution
 Can redstone be blacklisted from interacting with the charge pack? Don't know if applicable.

## Steps to Reproduce (for bugs)
   1.  Wear the gt++ charge pack (UV in my case) in your baubles belt slot
   2. Pick up a stack of redstone, either from AE2, the ground, a chest or cheat it in from NEI
   3. Get kicked from the server and lose the ability to connect until you delete player data.

## Context
It causes me to remove the charge pack every time I want to handle redstone in any way, and is supremely annoying. When mining, for example, and picking up anything that drops redstone dust, instant loss of player data.

This happens every time, removing the charge pack from baubles slot fixes it and stops it from happening.[ Here's a log](https://pastebin.com/1Rptx4iv) of the incident.

## Game Environment
Version is 2.0.7.5 from the official download repository

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version: gregtech-5.09.33.16
 * IC2 version: industrialcraft-2-2.2.828a-experimental
 * Java version: java version "1.8.0_211"
 * Operating System: Windows 10 x64

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ X]    Using GT:NH/GT:New Horizons?
 - [X ]    Single Player?
 - [ X]    Multi Player?

**Comment by Technus** [comment]
Ah yes redstone is a power source.

**Comment by Zafaranec** [comment]
I have similar problem with supreme pizza gloves, after equip him in baubles slot, [here](https://pastebin.com/TvHBcqZf) is what say server, i must recover player data from backup, I know this item is not too important, but...
