### ISSUE TITLE
slow building blocks crashes

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [alkcorp/GTplusplus#506]
# Issue Title  

## Expected Behavior
should be decatovated when i remove it
## Current Behavior
it crashes the server instead while being stuck in the ring slot

## Steps to Reproduce (for bugs)
 1.wear the ring, activate it (was on the top slot if that helps)
 2.remove the ring
3. well done! you've obtained a crash report!

## Game Environment
 * Modpack Name: GTNH
 * Version used:2.0.7.5

Also include:
 * Gregtech version: in the pack
 * IC2 version: in gtnh
 * Java version:8 update 211
 * Operating System: windows 7
 
### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [ x]    Multi Player?

**Comment by draknyte1** [comment]
Can you actually give me a crash report?

**Comment by Wolozo7** [comment]
Related to this, I got rid of the ring by dying. But the crouching effect persisted after the death.

**Comment by PoptartOverlord-Xabedo** [comment]
ah sorry, i forgot about this issue as i got busy around that time, you should ask the official GTNH staff for the crash report since it was in server the server.
 also @Wolozo7 try either relogging or restarting client, that worked for me

**Comment by Wolozo7** [comment]
Restarting the client worked, ty. Before that, the functionality of the ring was still there despite it no longer being in my inventory.

**Comment by draknyte1** [comment]
Should be fixed next update. 
Already is in the dev releases.
