### ISSUE TITLE
missing recipy for hydrogen peroxide

### ISSUE THREAD

**Issue by botn365** [alkcorp/GTplusplus#509]
# Issue Title  
## Expected Behavior

the recipy to make hydrogen peroxide from  2-ethylanthrahydroquinone

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used:2.0.7.5
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version:
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by kekzdealer** [comment]
![image](https://user-images.githubusercontent.com/31353359/62064629-91267580-b22d-11e9-8c5a-360bd706e76b.png)
Confirmed that this is the only recipe for hydrogen peroxide in 2.0.7.5. Lithium Hydoperoxide requires hydrogen peroxide to be produced itself.
