### ISSUE TITLE
[Request] Add painting functionality to Multiblocks

### ISSUE THREAD

**Issue by finkledoodle** [alkcorp/GTplusplus#510]
# Issue Title  
For a simple aesthetic/quality of life increase, it would be very appreciated if players could use the painting functionality that works for Gregtech singleblock machines (dying them various colors) on GT and GT++ multiblocks. As of now I know of no way to change the color of various casings/control blocks/hatches/buses when they are tied to a multiblock. I know it is a minor issue, but it would be really nice if, for example, if I didn't have to look at this green ruin the nice blue coloring of this area.
![2019-07-09_21 39 52](https://user-images.githubusercontent.com/12854704/60941014-6c745900-a292-11e9-9b79-fcab3b764dea.png)

**Comment by draknyte1** [comment]
Without making every casing a tile entity or implementing 15 extra colour variations of the existing blocks (That's another 16 * 15 * 6 blocks), it's impossible.

Making all the casings Tile Entities is.. Also not a great idea, which I'm not going to forcefully inject into GT (Would be required to have all casings paintable).
