### ISSUE TITLE
wireless charging wont work

### ISSUE THREAD

**Issue by botn365** [alkcorp/GTplusplus#518]
## Expected Behavior
to charge my armor and porteble scanner

## Current Behavior
it does not charge anyting and does not show chat message
even when leaving and entering its range

## Context
on SSP world

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons? 2.0.7.5
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Did you adjust their behaviour at all?

I think it’s quirky, but functional as is. Was gonna leave open as a reminder to fix it someday x)
