### ISSUE TITLE
Thermal Boiler does not accept lava filter inserted into input bus

### ISSUE THREAD

**Issue by Barokko** [alkcorp/GTplusplus#532]
Expected Behavior
It should be possible to insert new lava filter into thermal boiler through Input Bus

Current Behavior
It is only possible to insert finter into controller's GUI slot. 

Steps to Reproduce (for bugs)
 1. Setup Thermal Boiler for lava processing
 2. Insert Lava Filter into Input Bus
 3. Nothing happens

Game Environment
GT++ 1.7.03.01
GTNH 2.0.7.5

Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Fixed.
