### ISSUE TITLE
Small input buffer in chemical dehydrator

### ISSUE THREAD

**Issue by barsikus007** [alkcorp/GTplusplus#537]
# Issue Title  
 
![image](https://user-images.githubusercontent.com/37113583/63910439-59c70680-ca2f-11e9-9d9b-5d11e18e06ed.png)
machine input tank isn't enough for recipe
I playing on GTNH's official server ETA

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 
 1.
 2.

## Context
 How has this issue affected you? What are you trying to accomplish? 
 Providing context helps us come up with a solution that is most useful. 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.0.7.5
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version: GTNN latest
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by barsikus007** [comment]
Same issue with 
![image](https://user-images.githubusercontent.com/37113583/63910529-c3dfab80-ca2f-11e9-9645-911b945b04c3.png)
mobessence
max input tank of brewery os 1332

**Comment by draknyte1** [comment]
The second one isn’t an issue. 
Use a PA.
