### ISSUE TITLE
GT++ Naquadah reactor XII didn't recognised as formed multiblock

### ISSUE THREAD

**Issue by Josh5minus1** [alkcorp/GTplusplus#539]
# Issue Title  
 Multiblock structure not forming

## Expected Behavior
The controller block should not tell incomplete structure anymore  

## Current Behavior
The tooltip wad followed carefully but still says incomplete structure.

## Possible Solution
 Fix the tooltip to match the correct structure 

## Steps to Reproduce (for bugs)
 1.  Just build the Large Naquadah Reactor. 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNewHorizons
 * Version used: 2.0.7.5
 * Download Link if possible: -----

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version: 
 * IC2 version:
 * Java version:
 * Operating System:

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [x ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Tooltip doesn’t reflect the actual construction of the multiblock. It’s not functional nor even craftable, so not something I consider an issue either.

**Comment by Josh5minus1** [comment]
Oh, it's not yet implemented.
