### ISSUE TITLE
Chemical Bath Mode on Ore washer multiblock doesn't work. (GT++ 1.7.02.99/1.7.03.01 in-game, GTNH 2.0.7.5)

### ISSUE THREAD

**Issue by weschaos** [alkcorp/GTplusplus#542]
I don't want to strike out or delete the below, but now that mitchej123 (on the GTNH discord) has pointed out to me that the chem bath mode requires water to fill the machine before it'll start processing chem bath recipes, this is mostly a documentation issue. Nowhere in the tooltip is this suggested, and I didn't even think to look in the code, which is my negligence. Nonetheless, I think the ore washer should be changed to reflect it, since the water requirement isn't specified anywhere and defies the requirements of the single machines.

---------------------

Regardless of what I try, the Ore Washing Plant multiblock doesn't seem to respond to anything when set to chemical bath. The hatches are full, the machine is powered and the controller reports no issues. The identical ore washing plant that I built next to it has no such problem when running in water mode. Putting in crushed ores does nothing.

## Expected Behavior
Washing tank should fill with mercury/sodium persulfate and process recipes as if it were a single-block chemical bath.

## Current Behavior
Does none of the above. Additionally, the input hatch isn't accepting sodium persulfate when part of the formed structure, nor does it accept other chemical bath fluids such as molten epoxid.

## Possible Solution
Recipes might not be added?

## Steps to Reproduce (for bugs)
1. Build multiblock
2. Screwdriver Controller to switch to chemical bath mode
3. Attempt to insert fluids (mercury gets accepted for some reason)

## Context
I built three ore washers, one for each of the common ore processing lines. They share walls for what that's worth.

## Game Environment
GTNH 2.0.7.5
GT++ 1.7.02.99 in the folder/1.7.03.01 in-game,

Also include:
 * Gregtech version: 5.09.33.16
 * IC2 version: 2.2.828-experimental
 * Java version: 64bit 8.0.1910.12
 * Operating System: Win10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Fixed.
