### ISSUE TITLE
All GT++ Multiblocks don't need core module

### ISSUE THREAD

**Issue by Kiwi233** [alkcorp/GTplusplus#543]
Which modpack version are you using?
#2.0.7.5

![image](https://user-images.githubusercontent.com/42833050/64482822-7d5a3000-d22b-11e9-8fb7-62999b410aff.png)

I test these GT++ Multiblocks, all of them don't need core module, some of them with core module will show "incomplete structure"(Ore Washer, Thermal Centrifuge, Amazon Prime, Energy Station).
https://github.com/GTNewHorizons/NewHorizons/issues/4877

Did GT++ cancel the core module?

**Comment by ScriptedPiky** [comment]
This was intentional as multiblocks do not need cores after a certain point in GTNH's version history (post v6.2+?). This was done due to various complaints about it when the cores were first introduced and were made optional in the config file of GT++ (or were hardcoded to be off).
