### ISSUE TITLE
extra outputs on the sifter and macerator v17.03.01

### ISSUE THREAD

**Issue by sthegreat** [alkcorp/GTplusplus#554]
## Expected Behavior
No bonus output for the sifter or macerator

## Current Behavior
Bonus output for the sifter and macerator. The sifter one makes bart's platinum processing give a lot more than it should due to how the looping works in the recipes so pls fix that one at least.

## Possible Solution
behavior appears to be here
https://github.com/alkcorp/GTplusplus/blob/5d53f87c91137166fceb2ae6d84c65d0eb8910be/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialSifter.java#L118
 
and here
https://github.com/alkcorp/GTplusplus/blob/5d53f87c91137166fceb2ae6d84c65d0eb8910be/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialMacerator.java#L112
## Steps to Reproduce (for bugs)
 Do a big test of either multi in creative and compare your output with the expected output

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  gtnh
 * Version used: 2.0.7.6 beta

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
I suggest @bartimaeusnek checks for GT++ and makes the output chances lower... Not really sure how that is my concern there...
