### ISSUE TITLE
GT Multiblock Sifter has different outputs compared to singles

### ISSUE THREAD

**Issue by observeroftime02** [alkcorp/GTplusplus#555]
## Expected Behavior
I would expect the multi sifter to have the same output chances than the singles, but this is not the case.

## Current Behavior
Currently, the multiblock sifter has a 12% bonus on output chances. [This piece of code here](https://github.com/alkcorp/GTplusplus/blob/5d53f87c91137166fceb2ae6d84c65d0eb8910be/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialSifter.java#L118) is the relevant one.

## Possible Solution
Change the value to 10000 and it will output on par with single block sifters.

## Steps to Reproduce (for bugs)
I did run some tests. Input was 10 chests of purified salt ore, then I macerated the outputs to get dusts.

```
Single Blocks    : 160147 Dust, 124483 Small Dust
GT++             : 178915 Dust, 139428 Small Dust
```
As you can see here, the GT++ has a roughly 12 percent output bonus. I was told that the sifter does not have an output bonus, and that the code above was ignored. So i went ahead and changed the value to 10000,  and ran the same test again. 

```
Single Blocks    : 160147 Dust, 124483 Small Dust
GT++             : 159755 Dust, 124668 Small Dust
```

As you can see, now the output matches that of the singles. For good measure I changed the value to 5000, and ran the tests again

```
Single Blocks    : 159968 Dust, 124837 Small Dust
GT++             : 320313 Dust, 249126 Small Dust
```
Double the output this time.

## Context
I heard there was a bonus output. I've heard there is no bonus output. At one point the tooltip mentioned bonus output, then it didn't anymore. If the machine is not supposed to have a bonus output, then something is wrong, as it does currently have a 12% bonus output. Would be nice if it could mention that, to clear the confusion, or the  bonus % be removed entirely. 

## Game Environment
GTNH 7.6b

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Alternative solution implemented.
