### ISSUE TITLE
Add Blizz Rod lootpool drops to Evolved Cold Blazes (GalaxySpace)

### ISSUE THREAD

**Issue by ScriptedPiky** [alkcorp/GTplusplus#557]
As the title states, adding a loot pool for the Evolved Cold Blazes to drop 1-4 Blizz Rods would be a nice addition to them, since they have no real lootpool at all. Additional drops such as Blizz or even Cryotheum in small quantities dust could be interesting as well.

The mob comes from GalaxySpace and is only generated on a few 'cold' planets.

**Comment by Dream-Master** [comment]
@ScriptedPiky we could do it with the GTNH Core mod like we did it for Lich bones.

**Comment by draknyte1** [comment]
It makes the most sense I do it. It’s not inherently GTNH specific & I already have similar for other mobs.

**Comment by Dream-Master** [comment]
i do with config more optinal.

**Comment by draknyte1** [comment]
It’s really not and I’ll be adding it regardless of what you do. So you’re doing pointless work. 

https://github.com/alkcorp/GTplusplus/blob/4d769b87aca6481b59f6894247895b9d2bd993b1/src/Java/gtPlusPlus/core/common/CommonProxy.java#L242

**Comment by Dream-Master** [comment]
so far you add a config do it :)
