### ISSUE TITLE
[Suggestion] Make power station compatible with energy detector cover

### ISSUE THREAD

**Issue by Auge103** [alkcorp/GTplusplus#562]
# Issue Title  
**Power station should be compatible with energy detector cover**

## Expected Behavior
An energy detector cover attached to the power station controller block should emit a redstone signal with its signal strength depending on the amount of stored energy inside the power station.

## Current Behavior
An energy detector cover attached to the power station controller block does not emit any signal at all.

## Possible Solution
Let the energy detector cover emit the energy output, just like battery buffers do

## Steps to Reproduce (for bugs)
 1. Place working power substation and fill with energy. Place working battery buffer and fill with batteries + energy.
 2. Attach energy detector cover to power substation controller block. Place energy detector cover to battery buffer block.
3. Put redstone next to the cover and measure the signal strength.
4. Battery buffer will output signal strength depending on battery charge level. The power station will always emit a zero strength signal.

## Context
The power station is an energy containing multiblock, which usually replaces the single block battery buffers in later tech tiers. Battery buffers do output their energy storage as redstone signal when an energy detector cover is attached. This is critical for automated energy production (e.g. turbines shut down when batteries are full and restart when batteries are near empty)

So the power station controller should output the stored energy as well when an energy detector cover is attached. Without, it is basically impossible to simply automate wasteless energy production.

## Game Environment
Modpack: GT New Horizons 2.0.7.5, 
but tested with only GT5u and GT++ as well (latest versions)

Also include:
 * Gregtech version: 5.09.33.16
 * IC2 version: 2.2.2.828a
 * Java version: 1.8.0.221
 * Operating System: Win 10

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
No idea how. 
The cover itself probably needs code adjustment, so highly unlikely it’ll ever be supported.

**Comment by botn365** [comment]
for me the energy detector cover has always worked from 7.5 up to on of the latest versions of gt++

**Comment by Auge103** [comment]
Apparently the session I tested this in was bugged. Did another test in a fresh world, it works now. Closed.
