### ISSUE TITLE
Solution and Idea to the Sifter and Maceration Multiblock

### ISSUE THREAD

**Issue by ScriptedPiky** [alkcorp/GTplusplus#563]
For those unaware of the current discussions relating to the Sifter: https://github.com/alkcorp/GTplusplus/issues/554 and https://github.com/alkcorp/GTplusplus/issues/555.

To reiterate and allow more information, due to a specific line of code listed below, the `8800` value dedicates the percentage drop chances that affect the Sifter's output. The lower the number, the more "higher" chances that you will receive. For instance, if I were to change `8800` to `10000` the chance would be normal drop chances. If it were changed to `7500` you'll now have a 25% bonus boost to the outputs.

Bart told me he has recently added a way that fixes this Sifter issue, though it is untested and needs confirmation that it works.
https://github.com/alkcorp/GTplusplus/blob/5d53f87c91137166fceb2ae6d84c65d0eb8910be/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialSifter.java#L118

Now that we've got that out of the way, let's get to the solution/idea. Introducing... an addon for the Sifter and possibly the Maceration; the **Precision Extraction Module**.

The Precision Extraction Module or PEM for short will carefully extract the valuables from the desired products with a significantly higher yield. However, in the same process, it will require more time for the recipe to complete.

The tiers go from ULV all the way to UHV or otherwise MAX in regular GT. Each voltage tier will increase the chances and time significantly. Percentage of chances per tier goes as follows:
`ULV 3%, LV 4.5%, MV 6%, HV 7.5%, EV 9%, IV 10.5%, LuV 12%, ZPM 13.5%, UV 15%, UHV/MAX 16.5%.`
In addition to this, the value of the tiered upgrade will reflect the increased time requirement by a factor of two and will add a flat time increase dependant on the upgrade tier. For instance, a ULV upgrade will add a 3% bonus benefit but will increase the overall recipe time by 6% and add 1 flat second that CANNOT be overclocked. The increased flat 1 second will apply after the overclocking is finished. The 6% time increase is affected by the overclocking. Multiple PEM's will not affect the multiblock's output chance. It only affects the Sifter and Maceration.

Thoughts? Please note, that the PEM is not required and the Sifter or Maceration multiblock can run freely without the upgrade.

**Comment by draknyte1** [comment]
Alternative solution implemented instead.
