### ISSUE TITLE
dust items don't render OVERLAY layer

### ISSUE THREAD

**Issue by leagris** [alkcorp/GTplusplus#567]
# Dust items don't render the `_OVERLAY` layer

GT++ `dust`, `dustSmal` and `dustTiny` does not render the dust overlays.
Possibly other items affected.
Issue is followup of https://github.com/alkcorp/GTplusplus/issues/188

 Provide a general summary of the issue in the Title above, 
 Something descriptive and related to the issue + Mod Version in [].
 Example `Custom GT++ Alveary Frame Blocks do not work [v1.5.0-alpha]`

## Expected Behavior
Render dusts with OVERLAY like Gregtech does:
![image](https://user-images.githubusercontent.com/1111474/68807859-e5ccef80-0668-11ea-8ac3-73b8ef9e6416.png)

## Current Behavior
dustMaterial, dustSmalMaterial, dustTinyMaterial don't render their _OVERLAY
Similar issue as https://github.com/alkcorp/GTplusplus/issues/188 but with dusts

* `assets/gregtech/textures/items/materialicons/METALLIC/dust.png`
![dust](https://user-images.githubusercontent.com/1111474/68807331-ee70f600-0667-11ea-98cd-1f57931b1adc.png)
* `assets/gregtech/textures/items/materialicons/METALLIC/dust_OVERLAY.png`
![dust_OVERLAY](https://user-images.githubusercontent.com/1111474/68807365-fb8de500-0667-11ea-836f-5abd58f58e97.png)

⇒ GT++ only renders the first `dust.png` layer
![image](https://user-images.githubusercontent.com/1111474/68807649-8078fe80-0668-11ea-832a-85a5169410f1.png)

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  BeyondREality
 * Version used: DEV

Also include:
 * Gregtech version: 5.09.31
 * IC2 version: 2-2.2.828-experimental
 * Java version: OpenJDK Runtime Environment (build 1.8.0_232-ea-8u232-b09-0ubuntu1-b09)
 * Operating System: Linux

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Actually, this is false and was fixed inhttps://github.com/alkcorp/GTplusplus/issues/188 when you originally reported it. Some special use, non-autogenerated dusts do NOT use the overlay and that's due to their base class. 98% can and do show it fine.

https://github.com/alkcorp/GTplusplus/blob/DevTop/src/Java/gtPlusPlus/core/item/base/BaseItemComponent.java#L476

```
	@Override
	public IIcon getIconFromDamageForRenderPass(final int damage, final int pass) {
		if (CORE.ConfigSwitches.useGregtechTextures) {
			if(pass == 0) {
				return this.base;
			}
			return this.overlay;			
		}
		return this.base;
	}

	@Override
	public void registerIcons(final IIconRegister i) {

		if (CORE.ConfigSwitches.useGregtechTextures){
			this.base = i.registerIcon(getCorrectTextures());
			this.overlay = i.registerIcon(getCorrectTextures() + "_OVERLAY");
		}
		else {
			this.base = i.registerIcon(getCorrectTextures());
			//this.overlay = i.registerIcon(getCorrectTextures() + "_OVERLAY");
		}
	}
```

**Comment by leagris** [comment]
Well, it is not fixed in the `GT-PlusPlus-1.7.02.09.jar` I got from Curse.

**Comment by Dream-Master** [comment]
https://circleci.com/gh/alkcorp/GTplusplus

**Comment by leagris** [comment]
@Dream-Master How to access artifacts?

**Comment by Dream-Master** [comment]
@leagris login with your github account and link it.
