### ISSUE TITLE
the arc furnace multie block does not want to form

### ISSUE THREAD

**Issue by botn365** [alkcorp/GTplusplus#572]
# Issue Title  
 mad ethe multie block with al corect hatches and does not want to form
tried size 3 and 7 

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons? 2.0.7.7
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by Kiwi233** [comment]
![image](https://user-images.githubusercontent.com/42833050/72766029-47da4000-3c2a-11ea-9c70-6f80c2241bd8.png)
still cannot be formed
GTNH 2.0.8.3
Both SP and MP

**Comment by draknyte1** [comment]
What hatches are you using?

**Comment by Kiwi233** [comment]
UHV hatches/buses
