### ISSUE TITLE
large scale assembler does not want to exept the microprocessor circuit

### ISSUE THREAD

**Issue by botn365** [alkcorp/GTplusplus#573]
# Issue Title  
when trieng to outoinput the lv microprocessor the input bus does not want to except it
this is only a problem with the microprocessor and not the other lv circuits
## Expected Behavior
 If you're describing a bug, tell us what you expect should happen.   
 If you're suggesting a change/improvement, tell us how it should/could work.  

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons? 2.0.7.7
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
It’s actually a bug in the recipe maps. 

Same issue exists on single blocks and it’s not my issue to resolve.
