### ISSUE TITLE
[Feature Request] Make skybox in Void dimension of RandomThings mod changeable

### ISSUE THREAD

**Issue by Methes** [alkcorp/GTplusplus#586]
# Issue Title  
Skybox of Void dimension from mod Random Things is probably hardcoded to be black ugliness

## Expected Behavior
Would be nice for the skybox to be changeable by resourcepack

## Possible Solution
Your code magic.

## Game Environment
 * Modpack Name:  GTNH

**Comment by draknyte1** [comment]
Skybox is very hardcoded.
