### ISSUE TITLE
Pollution Scrubber with LE mode doesn't work when turbine durability is low

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#604]
# Issue Title  
Pollution Scrubber with LE mode doesn't work when turbine durability is low[1.7.02.99-pre]`

## Expected Behavior
The reduction in turbine durability lasts up to 50% and continues to work.
And can disassemble the turbine.

## Current Behavior
Turbine durability is reduced to 50% or less (1000 or less) and it stops working.
And can't disassemble the turbine....
![2020-01-11_00 52 39](https://user-images.githubusercontent.com/40425798/72166531-c2c28000-340c-11ea-8b92-9a87ae038b6a.png)
![2020-01-11_00 56 40](https://user-images.githubusercontent.com/40425798/72166837-5300c500-340d-11ea-9409-f854f539bbbd.png)

## Game Environment
 * Modpack Name:GT:New Horizons
 * Version used:ver2.0.7.5

Also include:
 * Gregtech version:5.09.33.16
 * IC2 version:2.2.828a-experimental
 * Java version:1.8.0_232
 * Operating System:CentOS7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Why do you think it would work if there’s no durability?

Disassembling the turbine was never intended and the functionality has been removed from GTNH. 

Everything is Working as intended.

**Comment by Dream-Master** [comment]
@yukieiji we disabled it otherwise you can get material back after you use it up to 1% thats not balanced.
Recycle it when it is new works so far ik.
