### ISSUE TITLE
[Feature Request] RF <-> GT/IC2 EU Converter Block

### ISSUE THREAD

**Issue by TwoTailedFox** [alkcorp/GTplusplus#611]
# Issue Title  
Since PowerConverters is unreliable with potential changes in GT5U, it would be great to have a way to convert RF to GT or IC2 EU to remove dependence on the mod mentioned above. Because of balance issues, the ratio of RF to EU should be included in a config file, as well as a toggle switch for it, because it would probably make GTNH easier.

## Expected Behavior
Ideally should be singular block, should include GUI to toggle any of the six sides for the following:

* RF IN
* RF OUT
* ICT EU IN
* ICT EU OUT
* GT EU IN
* GT EU OUT

Due to EU tier scaling, might be an idea for this block to scale similarly to how transformers do for increased EU requirements.

## Current Behavior
Does not exist

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Game Environment
N/A

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [x ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Just let me know how it works, if it's alright, feel free to close.
