### ISSUE TITLE
Operation of the multi-block machine is strange

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#613]
# Issue Title  
Operation of the multi-block machine is strange [GT-PlusPlus-1.7.04.449]`

## Current Behavior
Imported enough power, no problem with inputing materials, but not continuously worked.
It operates for a moment and stops repeatedly....
![2020-01-18_17 29 26](https://user-images.githubusercontent.com/40425798/72660952-26a20580-3a18-11ea-9e88-fa78712d1b8e.png)
![2020-01-18_17 29 29](https://user-images.githubusercontent.com/40425798/72660953-273a9c00-3a18-11ea-945f-a65212388de7.png)
![2020-01-18_17 29 35](https://user-images.githubusercontent.com/40425798/72660954-273a9c00-3a18-11ea-9f61-1833c9a36031.png)

Large centrifuges that made deuterium and tritium are in this state....

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:GT:NewHorizons  
 * Version used:ver2.0.8.1

Also include:
 * Gregtech version:gregtech-5.09.33.30
 * IC2 version:industrialcraft-2-2.2.828a-experimental
 * Java version:1.8.0_232
 * Operating System:CentOS7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
Consider updating.

**Comment by yukieiji** [comment]
Updated to Ver2.0.8.3 that a while ago, now works properly.
Thank you @draknyte1.

**Comment by yukieiji** [comment]
This issue recurred in GT-PlusPlus-1.7.05.53a in GTNH ver2.0.9.0beta2.

**Comment by yukieiji** [comment]
It also occurred in GTNH ver2.0.9.0 beta4, so please reopen.

**Comment by draknyte1** [comment]
Consider providing more details.

**Comment by yukieiji** [comment]
I'm sorry, I just forgot to install the muffler hatch.
