### ISSUE TITLE
[2.0.8.3] Volcanus can't smelt Nq/Nq+/HSS-S/etc... with HSS-G Coils + IV

### ISSUE THREAD

**Issue by DV666** [alkcorp/GTplusplus#620]
# Issue Title  
Volcanus can't smelt Nq/Nq+/Hss-s/etc... with HSS-G Coils and IV Energy Hatch since update 2.0.8.3.

## Expected Behavior
Since 2.0.8.3 GTNH, my volcanus can't smelt some ingots like Naquadah, Enriched Naquadah and Hss-s.
Conditions are respected (for example Nq+ required 7680 EU/t = IV and 5350 K = HSS-G with 5400K) but didn't work...

![image](https://user-images.githubusercontent.com/17729817/72690295-4c640300-3b1b-11ea-9d77-e1ee386c1953.png)

However, works perfectly with an EBF.

## Current Behavior
EBF can smelt theses ingots, Volcanus can't since this update.... :(

## Possible Solution
Sorry, big noob on programmation :D but plz fix it :]

![image](https://user-images.githubusercontent.com/17729817/72690242-a912ee00-3b1a-11ea-9ab2-c23046822907.png)

## Steps to Reproduce (for bugs)
- Build an EBF with IV Energy Hatch, some Argon or Radon and HSS-G Coils : Naquadah Dust + circuit=11 => OK
- Build a Volcanus with IV Energy Hatch, some Argon or Radon and HSS-G Coils : Naquadah Dust + circuit=11 => NOK... didn't launch the craft.

## Context
Since this new update, some craft are stuck... like LuV craft ou Nq+ rod for my generator.... x_x

## Game Environment
GTNH 2.0.8.3. Test on my MP server and SP.

 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

Thank you in advance \o/

**Comment by ScriptedPiky** [comment]
Can confirm that the Volcanus does not turn on even with Pyrotheum inside.
![2020-01-19_19 03 17](https://user-images.githubusercontent.com/41557212/72695783-a4384500-3aee-11ea-8aaf-9d42a3ea27c0.png)
![2020-01-19_19 04 05](https://user-images.githubusercontent.com/41557212/72695784-a4384500-3aee-11ea-8a88-64215330a63d.png)

Seems to consume 5 Blazing Pyortheum upon trying to start, but fails ever start, not even consuming the item inside despite having correct circuit(s), materials, gas, energy (full amperage), and so on.

**Comment by ScriptedPiky** [comment]
Actually, I can confirm that no other multiblock seems to work. The Cryo Freezer will run for a tiny bit then immediately stop and will refuse to turn on. Except this time both the Cryo Freezer and Centrifuge will refuse to turn on and will consume the recipe despite having enough energy.

**Comment by DV666** [comment]
Cryo freezer works fine on SP... but i found a little issue with it : you can't fill hatch when it's connected.

- You can fill it with cryotheum when you place it.
- When texture hatch changed (so become blue) : he can't accept cryotheum anymore... (test with ender io conduit, pump IV and steve's factory manager)

Make a video about that => [Here !](https://www.youtube.com/watch?v=mJYdLxulMYc)

I also see Cryo Freezer consume 10L Cryo per operation instead of 1L (seems... ?)

@botn365 It's possible to share me the fix ? :D I'm in tricky situation with my volcanus since this update.... ^^'

**Comment by botn365** [comment]
https://476-50003534-gh.circle-artifacts.com/0/home/circleci/repo/build/libs/GT-PlusPlus-1.7.04.476-dev.jar

**Comment by botn365** [comment]
for cryo freezer you have to use a cryothium cooling hatch not a normal input hatch

**Comment by DV666** [comment]
I am an idiot... woops ! So works perfectly indeed :D 

Try to use your fix @botn365 but game can't be launch (i disabled previous GT++ ofc)

[Crash-report](https://pastebin.com/xL31gvZW)

**Comment by botn365** [comment]
https://476-50003534-gh.circle-artifacts.com/0/home/circleci/repo/build/libs/GT-PlusPlus-1.7.04.476.jar
woops linked the wrong one

**Comment by DV666** [comment]
Test on SP : Volcanus with IV energy hatch + argon + HSS-G coil => OK !

Inject new jar on my server => Can smelt naquadah and HSS-S : Volcanus is back !

Thank you very much @botn365, you save my game :D 

(You can close if you want)
