### ISSUE TITLE
Recipe change suggestion: Dehydration ethylene

### ISSUE THREAD

**Issue by Ethryan** [alkcorp/GTplusplus#633]
In the dehydrator right now you input 2000L liquid Etanol and 2 empty cells to receive 1 etylene cell and 1 water cell.

My suggestion is to change it so that the water gets outputed as a fluid instead of put into a cell.

This is to ease early game automation so that the fluids can be split into different directions easier.

Copied from GTNH [#5475](https://github.com/GTNewHorizons/NewHorizons/issues/5475#issuecomment-580465135)

**Comment by Ethryan** [comment]
Phew, finally found the code that adds this recipe it is this:

https://github.com/alkcorp/GTplusplus/blob/eb92b20fc2eff899396ca41301030bab43d73986/src/Java/gtPlusPlus/core/item/chemistry/CoalTar.java#L52

**Comment by draknyte1** [comment]
I'm unsure why you found the need to find the recipe. (It serves no purpose beyond a useless comment)

You can use Round Robinators from LV to split the outputs evenly & IMHO item IO is easier to manage than Fluid IO. I don't see any reason to change this sorry.
