### ISSUE TITLE
Chemical Plant tooltip doesn't tell you what the CP tier does

### ISSUE THREAD

**Issue by Prometheus0000** [alkcorp/GTplusplus#634]
# Issue Title  
It says "Solid Casings dictate Chemical Plant tier", but there's nothing to say what this does.

## Expected Behavior
The next line should tell us what the tier does presumably.

## Possible Solution
Add tooltip text.

## Context
I have no idea why I would upgrade from steel to anything above that.

## Game Environment
GTNH 2.0.8.3

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
Look at the recipes in NEI, they’ve got a tier tooltip.
