### ISSUE TITLE
Can't build Dangote Distillus

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#637]
# Issue Title  
Can't build Dangote Distillus[GT-PlusPlus-1.7.04.471]

## Expected Behavior
Can be build correctly

## Current Behavior
Recognizes correctly up to height 12 but don't recognizes more and can't be build at height 26.

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment]
The tooltip literally says T2 is disabled.
