### ISSUE TITLE
Industrial wiremill broken at 283

### ISSUE THREAD

**Issue by Ngar1** [alkcorp/GTplusplus#640]
#### Which modpack version are you using?
283
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
existing wiremill say broken strukture
Picture of strukture (GUI in controller) changed but comment in NEI of controllerblock doesent changed. 

#
#### What do you suggest instead/what changes do you propose?
actualized Block Info

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ ]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x ]    Multi Player?

![grafik](https://user-images.githubusercontent.com/7759876/74605453-99120e00-50c8-11ea-9d94-ddf76e0c8feb.png)
![grafik](https://user-images.githubusercontent.com/7759876/74605459-a0d1b280-50c8-11ea-8128-240264870c36.png)

**Comment by botn365** [comment]
in reacent versions the case limit got fixed so check if you have 32 casings for it

**Comment by Ngar1** [comment]
yes, that was the problem. Now I have to work with relais, but I would thought, that more Input hatches are more server friendly. May be an idea to reduce the factory blocks?

**Comment by botn365** [comment]
i see no reason to decrease the count sinse it is posible to put al the recipes while only using 1 input hatch

**Comment by Ngar1** [comment]
with inventory cable, or chest with conv. (or?) - this ist realy better than more input hatches?

**Comment by botn365** [comment]
with item pipes and cover or chest if you
sure tps wise it isent better but this limit does making designing around it more interesting if you dont want to build more if them

**Comment by Ngar1** [comment]
I am more interested in better TPS than in "chest and pipe" transport systems as I used at LV age, because my world (I am at LuV) gets every time warnings of high ticks.
