### ISSUE TITLE
internal tank of advanced boiler [lv] is not capped at 32 buckets GTNH 2.0.8.3

### ISSUE THREAD

**Issue by boubou19** [alkcorp/GTplusplus#645]
## Expected Behavior
I let an advanced boiler [lv] fill its internal tank. I was expecting it to cap at 32 buckets like waila
and the portable scanner say.

## Current Behavior
It does not cap:
![2020-02-24_11 14 10](https://user-images.githubusercontent.com/12850933/75144227-d4c75c00-56f6-11ea-85aa-d1d1d8020bf6.png)
It will increase until it reach 64 buckets then it will fall at 48 bucket and will increase again.

## Steps to Reproduce (for bugs)
 1. setup an advanced boiler [lv]
 2. let it fills its internal tank with steam until "max"

## Game Environment
 * Modpack Name:  GTNH
 * Version used: 2.0.8.3

Also include:
 * Gregtech version: gregtech-5.09.33.30
 * IC2 version: industrialcraft-2-2.2.828a-experimental
 * Java version: 1.8.0_221
 * Operating System: Windows 7

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
WAILA issue. Same things happens to all boilers last I recall.
