### ISSUE TITLE
ore drilling plant work just in one chunk

### ISSUE THREAD

**Issue by Ngar1** [alkcorp/GTplusplus#646]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
DeepDark-World: 
place a ore driling plant and also reactivate a drilling plant from 2.0.7.5. Placed chunkloader (personal anchor) to get 27 aktiv chunks.
#
#### What happened instead? (Attach screenshots if needed)
Drilling just in the chunk of ore drilling plant
#
#### What do you suggest instead/what changes do you propose?
Drilling in all aktive chunks

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x ]    Multi Player?

**Comment by botn365** [comment]
not a gt++ isue
