### ISSUE TITLE
rename  essentia

### ISSUE THREAD

**Issue by Pnc6lx** [alkcorp/GTplusplus#647]
all the gt++ added essentia have a name like custom1. when the code still can be seen, i have find the correct name for these essentia in the code. please rename the essentia as the correct name。

**Comment by draknyte1** [comment]
They were removed long ago, lol.

**Comment by Pnc6lx** [comment]
> They were removed long ago, lol.

i can still see it in nei in gtnh2083, please rename it or totally delete it

**Comment by botn365** [comment]
iirc bartworks added them back so it wound crach the game if you had them in a save file before

**Comment by draknyte1** [comment]
Think they’re in the NH core mod. 

Not my issue to resolve.
