### ISSUE TITLE
Super Bus sort mode off didn't work

### ISSUE THREAD

**Issue by DV666** [alkcorp/GTplusplus#653]
### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

#### Which modpack version are you using?
2.0.8.4QF   
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I have a lot of small/tiny dust and i need to process very fast : i can't craft GT++ packager for the moment so i use processing array (IV with 16 Packagers HV)

![2020-03-08_13 38 37](https://user-images.githubusercontent.com/17729817/76163056-4c5ba900-6143-11ea-8f6b-3961cf86deb3.png)

I use 2 filters to send dust in quantities of 4 or 9 + sort mode disabled on input bus (HV) : that's works but not optimally. 
However, i have an GT++ issue with Super Bus.
When i disable sort mode, that's didn't work very wel after few seconds, processing array stuck because some dust remain on bus (have never this problem with classic input bus)

#
#### What do you suggest instead/what changes do you propose?
Need to fix mode sort off for super bus.

I hope to be clear on the problem, you can reproduce the machine's configuration in SP if needed.

Thanks in advanced !

**Comment by draknyte1** [comment]
I don’t implement sort mode. If it doesn’t work, it’s an issue in the normal bus sort code. Won’t fix.
