### ISSUE TITLE
Industrial Electrolyzer tooltip wrong?

### ISSUE THREAD

**Issue by chochem** [alkcorp/GTplusplus#658]
## Expected Behavior
I am electrolyzing water with an IV energy hatch. I expected energy usage of 30eu/t(base)x10(parallel)x0.9x4x4=4320 eu/t (2 overclocks) which is indeed the case and a water usage of 30L/s(base)x10x2.8x2x2=3360L/s which is not the case.

## Current Behavior
The water usage is about 6000L/s (+-200L/s).

## Possible Solution
It's hard to figure out the exact problem with looking into the code, but my best guess is that the industrial electrolyzer is not 180% faster (or x2.8) like it says in the tooltip, but actually is 400% faster (or x5), since then the expected water usage would be 30L/s(base)x10x5x2x2=6000L/s.

This should be easy to check in the code. If true, please change the tooltip. Otherwise there might be a problem with this specific recipe or with my calculations.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.

 * Modpack:  GTNH, single player
 * modpack version: 2.0.8.6
 * using GT-PlusPlus-1.7.05.20

**Comment by botn365** [comment]
20/2.8 = 7.1 or 7 
2 OC -> 7 /4 = 1.75 or 1
evrything is used with intergers where you dont have comma numbers

**Comment by chochem** [comment]
ah interesting, that makes sense I suppose. So thanks to rounding several times 20/2.8/2/2=1, gotcha. That is quite the powerful compound effect, good to know. (and don't tell 0lafe)
