### ISSUE TITLE
Hazmat/pollution related crash

### ISSUE THREAD

**Issue by Bluebine** [alkcorp/GTplusplus#673]
## Current Behavior
 If describing a bug, tell us what happens instead of the expected behavior. 
 If suggesting a change/improvement, explain the difference from current behavior. 

I'm on GTNH version .8.9, which ships with GT++ 1.7.05.Local-hazmatfix according to the file. Every 30 seconds to a minute, my game crashes with the following crash report:
https://pastebin.com/ytjqEm3R

## Steps to Reproduce (for bugs)
 Provide a link to a live example, or an unambiguous set of steps to 
 reproduce this bug. Include code to reproduce, if relevant. 

The crashing seems to be irrelevant of what I actually do- it just crashes, less than a minute after I open the world, every time I try. My world is pretty heavily polluted, and the crashlog mentions pollution, so I'd assume it relates to that somehow. 

## Context
 How has this issue affected you? What are you trying to accomplish? 
 Providing context helps us come up with a solution that is most useful. 

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.0.8.9
 * Download Link if possible:

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version: 5.09.33.38
 * IC2 version: 2.2.828a
 * Java version: 1.8.0_241 64-bit
 * Operating System: Windows 10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x ]    Using GT:NH/GT:New Horizons?
 - [x ]    Single Player?
 - [ ]    Multi Player?

**Comment by tyrannus00** [comment]
Pretty much the same is happening to me too, tho its noteworthy that i am in early steam age with just 1 of each basic steam machine type and i therefore dont have that much pollution in my world. The crash occured btw for on a local server. (GT:NH 2.0.8.9 too)
https://pastebin.com/sZPTXeck
