### ISSUE TITLE
Large Processing Factory fluid solidifier mode

### ISSUE THREAD

**Issue by GTNH-Colen** [alkcorp/GTplusplus#677]
# Issue Title  
 Fluid solidifier mode doesn't work.

## Expected Behavior
The fluid solidifier should work when the LPF is in misc mode with a programmed circuit of 22 according to the "Multi-machine manual". I'm unsure if this book is perhaps out of date as the tool tip does not include a fluid solidifier mode.

## Current Behavior
It does not process the recipe.

## Possible Solution
Either add the fluid solidifier (Preferred) or update the book/tooltip.

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.0.8.3
 * Download Link if possible

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by Prometheus0000** [comment]
Like I mentioned on discord, it _does_ work. I mentioned the tooltip thing in #666. Maybe it doesn't work on your version? It works on 2.0.8.8 with GT-PlusPlus-1.7.05.20.

**Comment by GTNH-Colen** [comment]
Yea you are correct, I just needed to come back and close this. For anyone wondering in future it does in fact work, the tooltip is simply incorrect (However the book isn't, use programmed circuit 22 on misc mode).
