### ISSUE TITLE
Railcraft's solid fuel boiler produces infinite steam without fuel usage

### ISSUE THREAD

**Issue by MrKorpiklaani** [alkcorp/GTplusplus#682]
# Railcraft's solid fuel boiler produces infinite steam without fuel usage. 

## Expected Behavior
Boiler should burn (use) fuel per work cycle. 

## Current Behavior
Boiler produces infinite steam without any fuel usage. Planks, sugar cane, coal, etc etc etc - no matter. 

## Possible Solution
Force fix by overide the burn code of boiler? idk.

## Steps to Reproduce (for bugs)
 1. Place solid fuel boiler
 2. Place low pressue boiler on it, so it becomes formed multublock structure.
 3. Add any kind of burnable solid fuel
 4. Profit.

## Context
 No context. Just placed and wanted to get steam for GT machines. Played with friend on internal server (via SSP - play LAN). 

## Game Environment
 * Modpack Name:  GTNH 
 * Version used: 2.0.8.9.dev4
 * Download Link if possible: http://downloads.gtnewhorizons.com/ClientPacks/GTNewHorizonsClient-1.7.10-2.0.8.9.dev4.zip
 * Addoptional installed mods: LiteLoader, VoxelMap, Optifine, ShadersModCore,  ServerPropertiesLAN

* Log: [fml-client-latest.log](https://github.com/alkcorp/GTplusplus/files/4490399/fml-client-latest.log)

 * Gregtech version: gregtech-5.09.33.40 unofficial
 * IC2 version: industrialcraft-2-2.2.828a-experimental
 * Java version:  JRE (build 1.8.0_221-b11)
 * Operating System: Windows 10

### Misc Info
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [x]    Multi Player? (via SSP)

**Comment by MrKorpiklaani** [comment]
The number of items also plays a role. If itemstack has only 1 item, it uses it. if > 1, generates steam without usage. But this happens random and i cant figure it completly out. Sometimes it doesnt uses even with 1 item. 

P.s. sorry for my bad english :)

**Comment by zfxstd** [comment]
@draknyte1 Sorry for big delay, didnt become email. Seems like its fixed now on latest version. Can be closed. 
Thanks!
