### ISSUE TITLE
LV semi-fluid gen only craftable in MV in GTNH

### ISSUE THREAD

**Issue by chochem** [alkcorp/GTplusplus#693]
## Expected Behavior
 I would expect each semi-fluid single block generator to be craftable in its tier.

## Current Behavior
The recipe for the LV semi-fluid gen needs molten bronze. All molten metals like bronze are only available in MV. I dont know if this is GTNH-specific or a general thing as I never played GT5u without the pack.

## Possible Solution
Change the fluid in the recipe to molten redstone or molten glass.

## Game Environment

Modpack Name: GTNH
Version used: 2.0.9.0-pre6-dev

which uses GT-PlusPlus-1.7.05.53a

**Comment by draknyte1** [comment]
That’s fucking dumb. 
Does bronze from a smeltery work? (Probably not)

**Comment by chochem** [comment]
no, bronze from a smeltery is not compatible.

> That’s fucking dumb.
I take it from this comment that this is a GTNH change to fluid extractor recipes? I actually like it because the pack doesn't give you all the GT machinery (or at least their usefulness) immediately, but spreads them out a bit over the early ages.

I dont know who changes which recipes for GTNH, so if this should go to the GTNH github instead, you just let me know.
