### ISSUE TITLE
Skookum Choocher

### ISSUE THREAD

**Issue by MineWitherMC** [alkcorp/GTplusplus#80]
Currently, Skookum Choocher is broken as:
1) its mode cannot be changed (tooltip says that shift-clicking works, but it doesn't) or is changed like a Division Sigil Activation Ritual.
2) if machines are broken with SC they drop dust instead of machine (eg, Basic Mixer drops 8 Steel dust)
GT++ 1.4.9.86, GT5U.29

**Comment by draknyte1** [comment]
After some investigation, it seems only certain machines break into dusts.
Using a HSS-E Skookum Choocher, I managed to 'wrench' most HV machines. Things like the Rock Breaker broke into 16x bronze dust though. I'll look into this some more.

The mode change works fine in SSP and only seems to be an issue in SMP.

**Comment by Technus** [comment]
Wrench level is still a thing. Similar thing happens for native gt wrenches if u try to use em when their tier is too low. (Tis why lead wrenches are garbo)
